version: '3.3'

services:
    mysql:
        image: mysql:8
        container_name: mysql_service
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: TianMiao
        volumes:
            - ./MySQL:/docker-entrypoint-initdb.d
    tomcat:
        image: tomcat:9-jre11
        container_name: tomcat_service
        ports:
            - 8080:8080
        volumes:
            - ./TianMiao/target/TianMiao.war:/usr/local/tomcat/webapps/TianMiao.war
            - ./opentelemetry-javaagent-all.jar:/opentelemetry-javaagent-all.jar
        # configuration of jaeger client
        environment:
            - OTEL_EXPORTER=otlp_span
            - OTEL_EXPORTER_OTLP_ENDPOINT=tempo:55680
            - OTEL_EXPORTER_OTLP_INSECURE=true
            - OTEL_RESOURCE_ATTRIBUTES=service.name=demo
            - JAVA_OPTS=-javaagent:/opentelemetry-javaagent-all.jar
        depends_on:
            - mysql
    tempo:
        image: grafana/tempo:0.5.0
        command: ["--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false"]
        ports:
            - 8081:80